// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1wN8ZnVPctWGrCMgBb3DtdFdKoMHE0TM',
    appId: '1:870158974038:web:d7401d312570d4f059cff7',
    messagingSenderId: '870158974038',
    projectId: 'padel-booking-app-1504d',
    authDomain: 'padel-booking-app-1504d.firebaseapp.com',
    storageBucket: 'padel-booking-app-1504d.firebasestorage.app',
    measurementId: 'G-ZRBX36XP5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChV3PE1pr5UH-H2e8a9SrU9u1kKXK3HL0',
    appId: '1:870158974038:android:11dae37ce31c887559cff7',
    messagingSenderId: '870158974038',
    projectId: 'padel-booking-app-1504d',
    storageBucket: 'padel-booking-app-1504d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz1svn5IQUKKqd-TriK7RA3uwj9I380b0',
    appId: '1:870158974038:ios:c757a8cb2c94bf2359cff7',
    messagingSenderId: '870158974038',
    projectId: 'padel-booking-app-1504d',
    storageBucket: 'padel-booking-app-1504d.firebasestorage.app',
    iosClientId: '870158974038-ibspvmlununegmca99jfm4i8m1t6mnba.apps.googleusercontent.com',
    iosBundleId: 'com.example.padelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz1svn5IQUKKqd-TriK7RA3uwj9I380b0',
    appId: '1:870158974038:ios:c757a8cb2c94bf2359cff7',
    messagingSenderId: '870158974038',
    projectId: 'padel-booking-app-1504d',
    storageBucket: 'padel-booking-app-1504d.firebasestorage.app',
    iosClientId: '870158974038-ibspvmlununegmca99jfm4i8m1t6mnba.apps.googleusercontent.com',
    iosBundleId: 'com.example.padelBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1wN8ZnVPctWGrCMgBb3DtdFdKoMHE0TM',
    appId: '1:870158974038:web:77b8f2bbb7ea70e659cff7',
    messagingSenderId: '870158974038',
    projectId: 'padel-booking-app-1504d',
    authDomain: 'padel-booking-app-1504d.firebaseapp.com',
    storageBucket: 'padel-booking-app-1504d.firebasestorage.app',
    measurementId: 'G-RXV5FT400G',
  );
}
